// This file is auto-generated by @hey-api/openapi-ts

export type NodeDefinition = {
    id: string;
    inputs?: {
        [key: string]: NodeInput;
    };
    outputs?: Array<(string)>;
    meta?: {
        description?: string;
        title?: string;
    };
};

export type NodeInput = {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'seed';
    value?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'boolean';
    value?: boolean;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'float';
    element?: 'slider';
    value?: number;
    min?: number;
    max?: number;
    step?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'integer';
    element?: 'slider';
    value?: number;
    min?: number;
    max?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'select';
    options?: Array<(string)>;
    value?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'vec3';
    value?: Array<(number)>;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'geometry';
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<(string)>;
    hidden?: boolean;
    type: 'path';
};

export type type = 'seed';

export type element = 'slider';

export type User = {
    id: string;
    name: string;
};

export type GetV1NodesByUserJsonData = {
    path: {
        user: string;
    };
};

export type GetV1NodesByUserJsonResponse = (Array<NodeDefinition>);

export type GetV1NodesByUserJsonError = unknown;

export type GetV1NodesByUserBySystemJsonData = {
    path: {
        system?: string;
        user: string;
    };
};

export type GetV1NodesByUserBySystemJsonResponse = (Array<NodeDefinition>);

export type GetV1NodesByUserBySystemJsonError = unknown;

export type GetV1NodesByUserBySystemByNodeIdby-.+jsonData = {
    path: {
        nodeId: string;
        system: string;
        user: string;
    };
};

export type GetV1NodesByUserBySystemByNodeIdby-.+jsonResponse = (NodeDefinition);

export type GetV1NodesByUserBySystemByNodeIdby-.+jsonError = unknown;

export type GetV1NodesByUserBySystemByNodeIdby-.+WasmData = {
    path: {
        nodeId: string;
        system: string;
        user: string;
    };
};

export type GetV1NodesByUserBySystemByNodeIdby-.+WasmResponse = (unknown);

export type GetV1NodesByUserBySystemByNodeIdby-.+WasmError = unknown;

export type PostV1NodesResponse = (NodeDefinition);

export type PostV1NodesError = unknown;

export type GetV1UsersUsersJsonResponse = (Array<User>);

export type GetV1UsersUsersJsonError = unknown;

export type GetV1UsersByUserIdJsonData = {
    path?: {
        userId?: string;
    };
};

export type GetV1UsersByUserIdJsonResponse = (User);

export type GetV1UsersByUserIdJsonError = unknown;