// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type NodeInput = {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'seed';
    value?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'boolean';
    value?: boolean;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'float';
    element?: 'slider';
    value?: number;
    min?: number;
    max?: number;
    step?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'integer';
    element?: 'slider';
    value?: number;
    min?: number;
    max?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'select';
    options?: Array<string>;
    value?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'seed';
    value?: number;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'vec3';
    value?: Array<number>;
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'geometry';
} | {
    internal?: boolean;
    external?: boolean;
    setting?: string;
    label?: string;
    description?: string;
    accepts?: Array<string>;
    hidden?: boolean;
    type: 'path';
};

export type NodeDefinition = {
    id: string;
    inputs?: {
        [key: string]: NodeInput;
    };
    outputs?: Array<string>;
    meta?: {
        description?: string;
        title?: string;
    };
};

export type User = {
    id: string;
    name: string;
};

export type PostNodesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/nodes';
};

export type PostNodesResponses = {
    /**
     * Create a single node
     */
    200: NodeDefinition;
};

export type PostNodesResponse = PostNodesResponses[keyof PostNodesResponses];

export type GetNodesByUserJsonData = {
    body?: never;
    path?: {
        user?: string;
    };
    query?: never;
    url: '/nodes/{user}.json';
};

export type GetNodesByUserJsonResponses = {
    /**
     * Retrieve nodes for a user
     */
    200: Array<NodeDefinition>;
};

export type GetNodesByUserJsonResponse = GetNodesByUserJsonResponses[keyof GetNodesByUserJsonResponses];

export type GetNodesByUserBySystemJsonData = {
    body?: never;
    path: {
        user: string;
        system?: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}.json';
};

export type GetNodesByUserBySystemJsonResponses = {
    /**
     * Retrieve nodes for a system
     */
    200: Array<NodeDefinition>;
};

export type GetNodesByUserBySystemJsonResponse = GetNodesByUserBySystemJsonResponses[keyof GetNodesByUserBySystemJsonResponses];

export type GetNodesByUserBySystemByNodeIdJsonData = {
    body?: never;
    path: {
        user: string;
        system: string;
        nodeId?: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}/{nodeId}.json';
};

export type GetNodesByUserBySystemByNodeIdJsonResponses = {
    /**
     * Retrieve a single node definition
     */
    200: NodeDefinition;
};

export type GetNodesByUserBySystemByNodeIdJsonResponse = GetNodesByUserBySystemByNodeIdJsonResponses[keyof GetNodesByUserBySystemByNodeIdJsonResponses];

export type GetNodesByUserBySystemByNodeId_byVersionJsonData = {
    body?: never;
    path: {
        user: string;
        system: string;
        nodeId: string;
        version?: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}/{nodeId}@{version}.json';
};

export type GetNodesByUserBySystemByNodeId_byVersionJsonResponses = {
    /**
     * Retrieve a single node definition
     */
    200: NodeDefinition;
};

export type GetNodesByUserBySystemByNodeId_byVersionJsonResponse = GetNodesByUserBySystemByNodeId_byVersionJsonResponses[keyof GetNodesByUserBySystemByNodeId_byVersionJsonResponses];

export type GetNodesByUserBySystemByNodeIdVersionsJsonData = {
    body?: never;
    path: {
        user: string;
        system: string;
        nodeId: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}/{nodeId}/versions.json';
};

export type GetNodesByUserBySystemByNodeIdVersionsJsonResponses = {
    /**
     * Retrieve a single node definition
     */
    200: Array<NodeDefinition>;
};

export type GetNodesByUserBySystemByNodeIdVersionsJsonResponse = GetNodesByUserBySystemByNodeIdVersionsJsonResponses[keyof GetNodesByUserBySystemByNodeIdVersionsJsonResponses];

export type GetNodesByUserBySystemByNodeIdWasmData = {
    body?: never;
    path: {
        user: string;
        system: string;
        nodeId?: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}/{nodeId}.wasm';
};

export type GetNodesByUserBySystemByNodeIdWasmResponses = {
    /**
     * Retrieve a node's WASM file
     */
    200: unknown;
};

export type GetNodesByUserBySystemByNodeId_byVersionWasmData = {
    body?: never;
    path: {
        user: string;
        system: string;
        nodeId: string;
        version?: string;
    };
    query?: never;
    url: '/nodes/{user}/{system}/{nodeId}@{version}.wasm';
};

export type GetNodesByUserBySystemByNodeId_byVersionWasmResponses = {
    /**
     * Retrieve a node's WASM file
     */
    200: unknown;
};

export type GetUsersUsersJsonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/users.json';
};

export type GetUsersUsersJsonResponses = {
    /**
     * Retrieve a single node definition
     */
    200: Array<User>;
};

export type GetUsersUsersJsonResponse = GetUsersUsersJsonResponses[keyof GetUsersUsersJsonResponses];

export type GetUsersByUserIdJsonData = {
    body?: never;
    path?: {
        userId?: string;
    };
    query?: never;
    url: '/users/{userId}.json';
};

export type GetUsersByUserIdJsonResponses = {
    /**
     * Retrieve a single node definition
     */
    200: User;
};

export type GetUsersByUserIdJsonResponse = GetUsersByUserIdJsonResponses[keyof GetUsersByUserIdJsonResponses];
